### ISSUE TITLE
Improve Decision Table Headers

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#494]
This issue acts as an epic for everything related to the new decision table header implementation.

Resources
* [Concept](https://github.com/bpmn-io/dmn-js/issues/490)
* [Demo](https://dmn-prototypes.netlify.com/column-editing-final)
* [Miro Board](https://miro.com/app/board/o9J_kuRBvoE=/)

------

**Visuals**
* [x] Remove Decision Id Component (#496)
* [x] Overwork Hit Policy Design (#497)
* [x] Implement new Column-Adding functionality (#498)
* [x] Implement new Column Header Layout (#499)
* [x] Implement new Context Menu Layout for Column Headers (#495) 

**Editing Capabilities**

* [x] Implement new column header editing component (#501)
* [x] Table columns can be resized (#500)

**Expression Language Support**

*not fully clarified yet*
* [ ] We only support FEEL (and JUEL?) as column expression languages
* [ ] Other expression languages should be marked as deprecated
* [ ] There exists a migration path to transform unsupported expression languages

**Possible Follow Up Topics**
* Sticky Headers, https://github.com/bpmn-io/dmn-js/issues/269

**Comment by pinussilvestrus** [comment]
Updated the Miro Board: https://miro.com/app/board/o9J_kuRBvoE=/

**Comment by barmac** [comment]
Done.
