### ISSUE TITLE
Release dmn-js@9.0

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#513]
__What is inside__

* [x] Updated logo + license terms (https://github.com/bpmn-io/dmn-js/issues/512)
* [x] Decision table UX improvements (https://github.com/bpmn-io/dmn-js/issues/494)
* [x] Align Literal Expressions Editor + Viewer (https://github.com/bpmn-io/dmn-js/issues/515)

__Release Checklist__

* 
*
*

----

Depends on https://github.com/bpmn-io/dmn-js/issues/494, https://github.com/bpmn-io/dmn-js/issues/512, https://github.com/bpmn-io/dmn-js/issues/515

**Comment by barmac** [comment]
Release is available on npm.
